# This workflow will build a Java project with Gradle

name: Build struckit and push a package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish artifact
        run: ./gradlew publish --no-daemon
        env:
          USERNAME: ${{ secrets.SENTINAL_USER }}
          TOKEN: ${{ secrets.SENTINAL_TOKEN }}
          COMMIT_HASH: ${{ github.sha }}
